
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn run lint
    - name: Build
      run: yarn run build --prod --base-href="/github-search/"
    - name: Test
      run: yarn run test
    - name: Deploy to GitHub Pages
      run: yarn run deploy